default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trello-clone_development

test:
  <<: *default
  database: trello-clone_test

production:
  <<: *default
  database: trello-clone_production
  username: user
  password: <%= ENV['TRELLO_DATABASE_PASSWORD'] %>
