image: python:3.4

before_script:
  - pip install -r requirements.txt
  - curl -SsL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 > /usr/local/bin/jq && chmod 755 /usr/local/bin/jq
  - mkdir public

test:
  stage: test
  script:
  - python validate.py schema.json < interview-questions.yml > questions.json
  - ./filter.sh | python render.py > questions.html

pages:
  stage: deploy
  script:
  - python validate.py schema.json < interview-questions.yml > public/interview-questions.json
  - python render.py < public/interview-questions.json > public/index.html
  - "(echo -n 'var interview_questions = {qs: '; jq -c . public/interview-questions.json ; echo '};' ) > public/interview-questions.js"
  - cp style.css public/

  artifacts:
    paths:
    - public
  only:
  - master
