default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dockerize-portfolio_development

test:
  <<: *default
  database: MyPortfolio_test

production:
  <<: *default
  database: dockerize-portfolio_production
  username: dockerize-portfolio
  password: <%= ENV['MYPORTFOLIO_DATABASE_PASSWORD'] %>
