# update postgresql.conf.
- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="listen_addresses = '*'"
    regexp='^listen_addresses.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="wal_level = 'hot_standby'"
    regexp='^wal_level.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="archive_mode = on"
    regexp='^archive_mode.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="archive_command = '/bin/true'"
    regexp='^archive_command.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="max_wal_senders = 10"
    regexp='^max_wal_senders.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="hot_standby = on"
    regexp='^hot_standby.*$'

- name: updating postgresql.conf
  sudo: true
  lineinfile: >
    dest={{pg_config_postgresql_conf}}
    line="shared_preload_libraries = 'repmgr_funcs'"
    regexp='^shared_preload_libraries.*$'

# registry as master node.
- name: register as master node
  sudo: true
  ignore_errors: true
  command: "repmgr -f /etc/repmgr/repmgr.conf master register"
