backend:
  name: git-gateway
  branch: master

media_folder: "src/images/uploads"
public_folder: "/src/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["article"] }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
