---
galaxy_info:
  author: Benjamin Coe <ben@npmjs.com>
  description: A role for installing npme OS dependencies (CouchDB, Nginx, Redis).
  min_ansible_version: 1.4
  version: 1.0.1
  license: ISC
  platforms:
    - name: Ubuntu
      versions:
      - precise
      - trusty
  categories:
    - npm
dependencies: []
