# what platform are we building for?
npme_platform: trusty

# npme build information.
npme_owner: npme
npme_group: npme
npme_home_directory: "/home/{{npme_owner}}"
npme_service_json_path: service.json

# npm build information.
npme_npm_version: npm@latest
npme_npm_bin: npm

# nginx build information.
npme_nginx_user: npme
npme_nginx_config_path: /etc/nginx
npme_nginx_log_path: /var/log/nginx

# CouchDB build information.
npme_couchdb_config_path: /etc/couchdb
npme_couchdb_owner: couchdb
npme_couchdb_group: couchdb
npme_couchdb_version: apache-couchdb-1.6.0
npme_couchdb_directory: "{{npme_home_directory}}/{{npme_couchdb_version}}"
npme_couchdb_tarball: "{{npme_couchdb_version}}.tar.gz"
npme_couchdb_tarball_url: "http://www.eu.apache.org/dist/couchdb/source/1.6.0/{{npme_couchdb_tarball}}"

# license information
npme_license_key: 6115d9c6-3010-43e4-86ad-b7ec829b8bf5
npme_license_email: ben@example.com
