version: '2'
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    working_directory: ~/code
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            apt-get update -q
            apt-get install -yq curl python
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Run basic tests
          working_directory: ~/code/tests
          command: |
            bash run_tests.sh | tee /tmp/test.log || true  # The test command always exits non-zero
            grep -v -E 'FAILED|ERROR' /tmp/test.log || exit 1
      - run:
          name: Run integration tests
          working_directory: ~/code/tests/integration
          command: |
            chmod +x set_cluster_name wait_for_es
            bash ./run.sh
