backend:
  name: git-gateway
  branch: master

media_folder: "src/images/uploads"
public_folder: "/src/images/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "beers"
    label: "Beers"
    folder: "beers"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Show", name: "show", widget: "boolean" }
  - name: "info-itabashi"
    label: "Info Itabashi"
    folder: "info/itabashi"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "info-yurakucho"
    label: "Info Yurakucho"
    folder: "info/yurakucho"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pagetype", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
